
services:
  # --- MySQL DB ---
  db:
    image: mysql:8.0
    container_name: geek_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geek_management
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: pass_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - geek_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:

networks:
  geek_network:
    driver: bridge
