spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:geek_management}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database: MYSQL
    show-sql: true

api:
  admin:
    name: ${DEFAULT_ADMIN_NAME:admin}
    login: ${DEFAULT_ADMIN_LOGIN:admin}
    pass: ${DEFAULT_ADMIN_PASS:admin}
  security:
    token:
      secret: ${JWT_SECRET:ggeek-secret-key}
